import { z } from "zod";

/**
 * OpenAI structured output schema for TaxFlow Spain AI extraction.
 * Validated server-side with Zod after every OpenAI response.
 */

export const caseSummarySchema = z.object({
  detected_workflow: z.string(),
  requested_service: z.string(),
  language: z.string(),
  priority: z.enum(["low", "medium", "high", "urgent"]).or(z.string()),
  analyst_summary: z.string(),
});

export const clientSchema = z.object({
  contact_name: z.string(),
  contact_email: z.string(),
  contact_phone: z.string(),
  company_name: z.string(),
  company_country: z.string(),
});

export const directorSchema = z.object({
  full_name: z.string(),
  first_name: z.string(),
  last_name_1: z.string(),
  last_name_2: z.string(),
  nationality: z.string(),
  passport_number: z.string(),
  passport_expiry_date: z.string(),
  date_of_birth: z.string(),
  place_of_birth_city: z.string(),
  place_of_birth_province: z.string(),
  place_of_birth_country: z.string(),
  foreign_tax_id: z.string(),
  address: z.string(),
  city: z.string(),
  province_region_state: z.string(),
  postal_code: z.string(),
  country: z.string(),
  country_code: z.string(),
  has_spanish_dni: z.boolean(),
  has_spanish_nie: z.boolean(),
  has_spanish_nif: z.boolean(),
  nif_m_received: z.boolean(),
  nif_m_number: z.string(),
});

export const companySchema = z.object({
  legal_name: z.string(),
  trading_name: z.string(),
  country_of_incorporation: z.string(),
  country_code: z.string(),
  registration_number: z.string(),
  foreign_tax_id: z.string(),
  vat_number: z.string(),
  registered_address: z.string(),
  city: z.string(),
  province_region_state: z.string(),
  postal_code: z.string(),
  business_activity: z.string(),
  website: z.string(),
  marketplace_used: z.string(),
  sells_in_spain: z.boolean(),
  sells_in_eu: z.boolean(),
  uses_amazon_fba: z.boolean(),
  stores_inventory_in_spain: z.boolean(),
  performs_intracommunity_b2b: z.boolean(),
  already_has_spanish_nif: z.boolean(),
  already_has_vat_number: z.boolean(),
  needs_roi_vies: z.enum(["yes", "no", "unknown"]).or(z.string()),
});

export const representativeSchema = z.object({
  full_name_or_company_name: z.string(),
  nif: z.string(),
  resident_in_spain: z.boolean().nullable(),
  representation_type: z.string(),
  representation_title: z.string(),
  power_of_attorney_present: z.boolean(),
  authorization_scope_summary: z.string(),
});

export const documentExtractionSchema = z.object({
  document_type: z.string(),
  file_name: z.string(),
  summary: z.string(),
  extracted_fields: z.record(z.string(), z.unknown()),
  warnings: z.array(z.string()),
  confidence_score: z.number().min(0).max(1),
});

export const aiExtractionOutputSchema = z.object({
  case_summary: caseSummarySchema,
  client: clientSchema,
  director: directorSchema,
  company: companySchema,
  representative: representativeSchema,
  documents: z.array(documentExtractionSchema),
  missing_information: z.array(z.string()),
  inconsistencies: z.array(z.string()),
  warnings: z.array(z.string()),
  confidence_score: z.number().min(0).max(1),
});

export type AiExtractionOutput = z.infer<typeof aiExtractionOutputSchema>;
export type CaseSummary = z.infer<typeof caseSummarySchema>;
export type ClientData = z.infer<typeof clientSchema>;
export type DirectorData = z.infer<typeof directorSchema>;
export type CompanyData = z.infer<typeof companySchema>;
export type RepresentativeData = z.infer<typeof representativeSchema>;
export type DocumentExtraction = z.infer<typeof documentExtractionSchema>;

/**
 * JSON Schema compatible object for OpenAI Structured Outputs API.
 * Used when calling responses.parse / chat.completions with response_format.
 */
export const aiExtractionJsonSchema = {
  name: "taxflow_extraction",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "case_summary",
      "client",
      "director",
      "company",
      "representative",
      "documents",
      "missing_information",
      "inconsistencies",
      "warnings",
      "confidence_score",
    ],
    properties: {
      case_summary: {
        type: "object",
        additionalProperties: false,
        required: [
          "detected_workflow",
          "requested_service",
          "language",
          "priority",
          "analyst_summary",
        ],
        properties: {
          detected_workflow: { type: "string" },
          requested_service: { type: "string" },
          language: { type: "string" },
          priority: { type: "string" },
          analyst_summary: { type: "string" },
        },
      },
      client: {
        type: "object",
        additionalProperties: false,
        required: [
          "contact_name",
          "contact_email",
          "contact_phone",
          "company_name",
          "company_country",
        ],
        properties: {
          contact_name: { type: "string" },
          contact_email: { type: "string" },
          contact_phone: { type: "string" },
          company_name: { type: "string" },
          company_country: { type: "string" },
        },
      },
      director: {
        type: "object",
        additionalProperties: false,
        required: [
          "full_name",
          "first_name",
          "last_name_1",
          "last_name_2",
          "nationality",
          "passport_number",
          "passport_expiry_date",
          "date_of_birth",
          "place_of_birth_city",
          "place_of_birth_province",
          "place_of_birth_country",
          "foreign_tax_id",
          "address",
          "city",
          "province_region_state",
          "postal_code",
          "country",
          "country_code",
          "has_spanish_dni",
          "has_spanish_nie",
          "has_spanish_nif",
          "nif_m_received",
          "nif_m_number",
        ],
        properties: {
          full_name: { type: "string" },
          first_name: { type: "string" },
          last_name_1: { type: "string" },
          last_name_2: { type: "string" },
          nationality: { type: "string" },
          passport_number: { type: "string" },
          passport_expiry_date: { type: "string" },
          date_of_birth: { type: "string" },
          place_of_birth_city: { type: "string" },
          place_of_birth_province: { type: "string" },
          place_of_birth_country: { type: "string" },
          foreign_tax_id: { type: "string" },
          address: { type: "string" },
          city: { type: "string" },
          province_region_state: { type: "string" },
          postal_code: { type: "string" },
          country: { type: "string" },
          country_code: { type: "string" },
          has_spanish_dni: { type: "boolean" },
          has_spanish_nie: { type: "boolean" },
          has_spanish_nif: { type: "boolean" },
          nif_m_received: { type: "boolean" },
          nif_m_number: { type: "string" },
        },
      },
      company: {
        type: "object",
        additionalProperties: false,
        required: [
          "legal_name",
          "trading_name",
          "country_of_incorporation",
          "country_code",
          "registration_number",
          "foreign_tax_id",
          "vat_number",
          "registered_address",
          "city",
          "province_region_state",
          "postal_code",
          "business_activity",
          "website",
          "marketplace_used",
          "sells_in_spain",
          "sells_in_eu",
          "uses_amazon_fba",
          "stores_inventory_in_spain",
          "performs_intracommunity_b2b",
          "already_has_spanish_nif",
          "already_has_vat_number",
          "needs_roi_vies",
        ],
        properties: {
          legal_name: { type: "string" },
          trading_name: { type: "string" },
          country_of_incorporation: { type: "string" },
          country_code: { type: "string" },
          registration_number: { type: "string" },
          foreign_tax_id: { type: "string" },
          vat_number: { type: "string" },
          registered_address: { type: "string" },
          city: { type: "string" },
          province_region_state: { type: "string" },
          postal_code: { type: "string" },
          business_activity: { type: "string" },
          website: { type: "string" },
          marketplace_used: { type: "string" },
          sells_in_spain: { type: "boolean" },
          sells_in_eu: { type: "boolean" },
          uses_amazon_fba: { type: "boolean" },
          stores_inventory_in_spain: { type: "boolean" },
          performs_intracommunity_b2b: { type: "boolean" },
          already_has_spanish_nif: { type: "boolean" },
          already_has_vat_number: { type: "boolean" },
          needs_roi_vies: { type: "string" },
        },
      },
      representative: {
        type: "object",
        additionalProperties: false,
        required: [
          "full_name_or_company_name",
          "nif",
          "resident_in_spain",
          "representation_type",
          "representation_title",
          "power_of_attorney_present",
          "authorization_scope_summary",
        ],
        properties: {
          full_name_or_company_name: { type: "string" },
          nif: { type: "string" },
          resident_in_spain: { type: ["boolean", "null"] },
          representation_type: { type: "string" },
          representation_title: { type: "string" },
          power_of_attorney_present: { type: "boolean" },
          authorization_scope_summary: { type: "string" },
        },
      },
      documents: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "document_type",
            "file_name",
            "summary",
            "extracted_fields",
            "warnings",
            "confidence_score",
          ],
          properties: {
            document_type: { type: "string" },
            file_name: { type: "string" },
            summary: { type: "string" },
            extracted_fields: {
              type: "object",
              additionalProperties: false,
              properties: {},
            },
            warnings: { type: "array", items: { type: "string" } },
            confidence_score: { type: "number" },
          },
        },
      },
      missing_information: { type: "array", items: { type: "string" } },
      inconsistencies: { type: "array", items: { type: "string" } },
      warnings: { type: "array", items: { type: "string" } },
      confidence_score: { type: "number" },
    },
  },
} as const;
