/**
 * TaxFlow Spain — TypeScript enums and constants
 * Mirrors Prisma enums for use in services and UI without DB coupling.
 */

export const USER_ROLES = {
  ANALYST: "ANALYST",
  SUPERVISOR: "SUPERVISOR",
  ADMIN: "ADMIN",
} as const;
export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

export const CASE_STATUSES = {
  NEW_CLIENT: "NEW_CLIENT",
  INTAKE_RECEIVED: "INTAKE_RECEIVED",
  AI_EXTRACTION_PENDING: "AI_EXTRACTION_PENDING",
  AI_EXTRACTION_COMPLETED: "AI_EXTRACTION_COMPLETED",
  WAITING_FOR_CLIENT_INFORMATION: "WAITING_FOR_CLIENT_INFORMATION",
  DOCUMENTS_PENDING: "DOCUMENTS_PENDING",
  DOCUMENTS_UPLOADED: "DOCUMENTS_UPLOADED",
  ANALYST_REVIEW: "ANALYST_REVIEW",
  MISSING_INFORMATION_REQUESTED: "MISSING_INFORMATION_REQUESTED",
  MODELO_030_REQUIRED: "MODELO_030_REQUIRED",
  MODELO_030_DRAFT_READY: "MODELO_030_DRAFT_READY",
  MODELO_030_APPROVED: "MODELO_030_APPROVED",
  MODELO_030_SUBMITTED: "MODELO_030_SUBMITTED",
  WAITING_FOR_TAX_AUTHORITY_RESPONSE: "WAITING_FOR_TAX_AUTHORITY_RESPONSE",
  NIF_M_RECEIVED: "NIF_M_RECEIVED",
  MODELO_036_ACTIVE: "MODELO_036_ACTIVE",
  MODELO_036_DRAFT_READY: "MODELO_036_DRAFT_READY",
  MODELO_036_APPROVED: "MODELO_036_APPROVED",
  VAT_ROI_REVIEW: "VAT_ROI_REVIEW",
  VAT_ROI_SUBMITTED: "VAT_ROI_SUBMITTED",
  COMPLETED: "COMPLETED",
  ON_HOLD: "ON_HOLD",
  REJECTED: "REJECTED",
} as const;
export type CaseStatus = (typeof CASE_STATUSES)[keyof typeof CASE_STATUSES];

export const CHECKLIST_STATUSES = {
  PENDING: "PENDING",
  UPLOADED: "UPLOADED",
  AI_PROCESSED: "AI_PROCESSED",
  NEEDS_REVIEW: "NEEDS_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  NOT_APPLICABLE: "NOT_APPLICABLE",
} as const;
export type ChecklistStatus =
  (typeof CHECKLIST_STATUSES)[keyof typeof CHECKLIST_STATUSES];

export const CHECKLIST_CATEGORIES = {
  MODELO_030: "MODELO_030",
  MODELO_036: "MODELO_036",
  VAT: "VAT",
  ROI_VIES: "ROI_VIES",
  GENERAL: "GENERAL",
} as const;
export type ChecklistCategory =
  (typeof CHECKLIST_CATEGORIES)[keyof typeof CHECKLIST_CATEGORIES];

export const DETECTED_WORKFLOWS = {
  MODELO_030: "MODELO_030",
  NIF_M: "NIF_M",
  MODELO_036: "MODELO_036",
  VAT: "VAT",
  ROI_VIES: "ROI_VIES",
  COMBINED: "COMBINED",
  UNKNOWN: "UNKNOWN",
} as const;
export type DetectedWorkflow =
  (typeof DETECTED_WORKFLOWS)[keyof typeof DETECTED_WORKFLOWS];

export const SUGGESTED_STATUSES = {
  MODELO_030_REQUIRED: "MODELO_030_REQUIRED",
  MODELO_036_ACTIVE: "MODELO_036_ACTIVE",
  VAT_ROI_REVIEW: "VAT_ROI_REVIEW",
  DOCUMENTS_PENDING: "DOCUMENTS_PENDING",
  ANALYST_REVIEW: "ANALYST_REVIEW",
} as const;
export type SuggestedStatus =
  (typeof SUGGESTED_STATUSES)[keyof typeof SUGGESTED_STATUSES];

export const SOURCE_TYPES = {
  EMAIL: "EMAIL",
  CRM: "CRM",
  DOCUMENT: "DOCUMENT",
  MANUAL: "MANUAL",
  AI_INFERENCE: "AI_INFERENCE",
} as const;
export type SourceType = (typeof SOURCE_TYPES)[keyof typeof SOURCE_TYPES];

export const AUDIT_ACTIONS = {
  CASE_CREATED: "CASE_CREATED",
  EMAIL_INGESTED: "EMAIL_INGESTED",
  CRM_RECORD_INGESTED: "CRM_RECORD_INGESTED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  AI_EXTRACTION_STARTED: "AI_EXTRACTION_STARTED",
  AI_EXTRACTION_COMPLETED: "AI_EXTRACTION_COMPLETED",
  AI_EXTRACTION_FAILED: "AI_EXTRACTION_FAILED",
  FIELD_AUTOFILLED: "FIELD_AUTOFILLED",
  FIELD_CORRECTED: "FIELD_CORRECTED",
  FIELD_APPROVED: "FIELD_APPROVED",
  FIELD_REJECTED: "FIELD_REJECTED",
  CASE_CLASSIFIED: "CASE_CLASSIFIED",
  CHECKLIST_GENERATED: "CHECKLIST_GENERATED",
  CHECKLIST_ITEM_UPDATED: "CHECKLIST_ITEM_UPDATED",
  STATUS_CHANGED: "STATUS_CHANGED",
  NIF_M_MARKED_RECEIVED: "NIF_M_MARKED_RECEIVED",
  MODELO_030_DRAFT_GENERATED: "MODELO_030_DRAFT_GENERATED",
  MODELO_036_DRAFT_GENERATED: "MODELO_036_DRAFT_GENERATED",
  REVIEW_PACK_GENERATED: "REVIEW_PACK_GENERATED",
  HUMAN_APPROVAL_COMPLETED: "HUMAN_APPROVAL_COMPLETED",
  AEAT_PREPARATION_COMPLETED: "AEAT_PREPARATION_COMPLETED",
  RECEIPT_UPLOADED: "RECEIPT_UPLOADED",
  CASE_COMPLETED: "CASE_COMPLETED",
} as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AI_INPUT_TYPES = {
  EMAIL: "EMAIL",
  CRM: "CRM",
  DOCUMENT: "DOCUMENT",
  MANUAL: "MANUAL",
  WEBHOOK: "WEBHOOK",
} as const;
export type AiInputType = (typeof AI_INPUT_TYPES)[keyof typeof AI_INPUT_TYPES];

export const HUMAN_REVIEW_CONFIDENCE_THRESHOLD = 0.85;
